# Human friendly display name for the workflow
name: Build - HTML

# Event triggers that trigger this workflow.
on:
    # Allows you to manually trigger this workflow from the GitHub UI.
    workflow_dispatch:

    # Allows this workflow to be called by other workflows.
    workflow_call:

    # Triggers the workflow on push or pull request events to the main branch.
    push:
        branches: [ main ]
    pull_request:
        branches: [ main, public ]

# List of isolated execution environments for this workflow.
jobs:
    Build-Html:
        # Human friendly display name for the job
        name: Build - HTML

        # Operating system environment for the job's steps to run on.
        runs-on: ubuntu-latest

        # Least privilege permissions for the job's steps to run with.
        permissions:
            attestations: write
            contents: read
            id-token: write
        
        # Set of steps to be executed in the job.
        steps:
            # Check out the repository's files into the runner so that it can work with them.
            - name: Clone Repository to Runner
              uses: actions/checkout@v6

            # Set up the Python runtime on the runner for use in subsequent steps.
            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                  python-version: '3.13'

            # Install the dependencies for building the documentation.
            - name: Install Dependencies
              run: pip install -r requirements.txt

            # Build the documentation into static HTML files.
            - name: Build Documentation
              run: zensical build

            # Zip the compiled HTML files for upload into other workflows
            - name: Zip Compiled Files
              working-directory: site
              run: zip -r -9 ../docs.zip .

            # Cryptographically attest to the compiled HTML files for use in other workflows that require a verifiable claim of provenance.
            - name: Attest Compiled File
              uses: actions/attest@v4
              with:
                subject-path: docs.zip

            # Upload the compiled HTML files as an artifact for use in other workflows.
            - name: Upload Compiled Files
              uses: actions/upload-artifact@v7
              with:
                name: Static-HTML
                path: docs.zip